### ISSUE TITLE
Use better naming and tagging in metric name

### ISSUE THREAD

**Issue by jorkzijlstra** [Segence/kamon-jmx-collector#12]
@robvadai 

We have currently trying to implement some dashboards using the latest version of the library. It turns our that is quite impossible to do due to the naming of the exported metrics.

The name is currently a concatenation of the path to the attribute. This does make make sure the metric is unique but it also makes selecting and grouping them not possible in f.i. Grafana.

Reference.conf: 
[reference.zip](https://github.com/Segence/kamon-jmx-collector/files/2045330/reference.zip)

Current output metrics example:
```
jmx_kafka_producer_per_broker_gns_global_entity_processor_e390e9cc_cdc3_4f4c_a5ce_6d9a7c85cd39_StreamThread_2_producer_node_131_request_rate{} 0.0
```
As you can see the `producer-id` and `node-id` are part of the name. Every restart of the application might result in a new id and it now requires an update of the Dashboards. You can might see that this is not a sustainable solution.

Using the `producer-id`, `node-id` (all the element in the query) as tags would fix this issue.

Fi: 
```
            //Kafka Producer Per-Broker Metrics
            {
                "metric-name": "kafka-producer-per-broker",
                "jmxQuery": "kafka.producer:type=producer-node-metrics,client-id=*,node-id=*",
                "attributes": [
                  { "name": "request-rate", "type": "punctual-gauge", "keys": [ ]  }
                ]
            },
```

Would result in something like:
```
jmx_kafka_producer_per_broker_request_rate{ype="producer-node-metrics",client-id={client-id}, node-id={node-id}"} 0.0
```
I think adding the `type` also as an tag would making the parsing of the query more easy.

**Comment by robvadai** [comment]
Hi @jorkzijlstra,

version `0.1.5` is published that fixes the issue.

**Comment by jorkzijlstra** [comment]
Hi @robvadai,

Thank you very much. I was a bit surprised that already see the change. Thanks for all the work you are putting into it.

Ill try to get it tested in the upcoming week. 

Regards, Jork

**Comment by jorkzijlstra** [comment]
@robvadai 
Looking real good. Thanks for all the work your putting into it.

Example output:
```
#jmx_kafka_producer_buffer_available_bytes{client_id="producer-1",type="producer-metrics"} 33554432.0
# TYPE jmx_kafka_producer_per_topic_record_send_rate gauge
jmx_kafka_producer_per_topic_record_send_rate{type="producer-topic-metrics",client_id="producer-1",topic="private_nieuwegein_native"} 0.0
# TYPE jmx_kafka_producer_batch_split_rate gauge
jmx_kafka_producer_batch_split_rate{client_id="producer-1",type="producer-metrics"} 0.0
# TYPE jmx_kafka_producer_request_latency_avg gauge
jmx_kafka_producer_request_latency_avg{client_id="producer-1",type="producer-metrics"} 13.0
# TYPE jmx_kafka_producer_waiting_threads gauge
jmx_kafka_producer_waiting_threads{client_id="producer-1",type="producer-metrics"} 0.0
# TYPE jmx_kafka_producer_requests_in_flight gauge
jmx_kafka_producer_requests_in_flight{client_id="producer-1",type="producer-metrics"} 0.0
# TYPE jmx_kafka_producer_record_size_max gauge
```

**Comment by robvadai** [comment]
Not a problem @jorkzijlstra, thank you for your valuable feedback.
