### ISSUE TITLE
Version 0.1.5 released but not visible on Bintray

### ISSUE THREAD

**Issue by oliverlockwood** [Segence/kamon-jmx-collector#19]
https://github.com/Segence/kamon-jmx-collector/blob/master/README.md#usage suggests using version `0.1.5`.

https://github.com/Segence/kamon-jmx-collector/releases/tag/0.1.5 suggests also that this release exists.

Bintray (https://bintray.com/segence/maven-oss-releases/jmx-collector) has only up to and including `0.1.4` available.
![screen shot 2018-07-11 at 08 26 21](https://user-images.githubusercontent.com/6017680/42556634-1f3eb3e6-84e4-11e8-84e4-c948f4dbe622.png)

Perhaps `0.1.5` has been uploaded to Bintray but not yet made public?

**Comment by robvadai** [comment]
Hi @oliverlockwood,

you're looking at the `jmx-collector` library which the Kamon JMX Collector depends on.

The repo for the Kamon JMX collector (this repo) is here: https://bintray.com/segence/maven-oss-releases/kamon-jmx-collector

**Comment by oliverlockwood** [comment]
@robvadai thanks for pointing me in the right direction.  I was only looking at that library since this repo's README linked me to it; I've raised PR #22 to try and prevent future such misunderstandings.  Hope that's helpful.
