### ISSUE TITLE
Wildcards in attribute name?

### ISSUE THREAD

**Issue by lacarvalho91** [Segence/kamon-jmx-collector#24]
Hi, 

I'm wondering if its possible to use a wildcard in the jmxQuery attribute name.

There are some Kafka consumer metrics where the attribute name follows the format of: $topicName-$partition.metric.

For example:
`test-topic-0.records-lag-avg`

However, I don't really want to configure each topic and partition individually, so I'm wondering if its possible to do something like:
`{"name": "*.records-lag-avg", "type": "punctual-gauge", "keys": []}`

From my experiments, I don't think it is currently possible. So I'm wondering if theres a way around this or whether this is something you would consider supporting?

**Comment by lacarvalho91** [comment]
Or maybe there's a configuration that would just allow us to collect every attribute under an MBean?

**Comment by lacarvalho91** [comment]
@robvadai I'm happy to look into raising a PR for this, if it isn't already possible - and you're happy with it.

**Comment by robvadai** [comment]
Hi @lacarvalho91 ,

is this closed issue help? https://github.com/Segence/kamon-jmx-collector/issues/5

There are some examples with wildcard queries with Kafka.

**Comment by lacarvalho91** [comment]
Hi @robvadai, I'm not sure it does since I'm looking for wildcards in attribute names config, not necessarily the `jmxQuery` config.

Although I'll admit my knowledge on this stuff isn't great so I could be missing something obvious!

**Comment by lacarvalho91** [comment]
For example I'd like to be able to do something like this:

```
      {
        "metric-name": "kafka-consumer-fetch-manager-metrics",
        "jmxQuery": "kafka.consumer:type=consumer-fetch-manager-metrics,client-id=*",
        "attributes": [
          {"name": "*.records-lag-max", "type": "punctual-gauge", "keys": []}
        ]
      }
```

The wildcard on `client-id=*` works since #5, but I don't think it is currently possible to do the wildcard in the `"name": "*.records-lag-max"`

**Comment by lacarvalho91** [comment]
I guess it would mainly require changes in [this method](https://github.com/Segence/kamon-jmx-collector/blob/20015e353dd69f9add49c42b91dcb448d08c379f/src/main/scala/kamon/jmx/collector/MetricCollector.scala#L46)

**Comment by lacarvalho91** [comment]
Updating my kafka-client meant that those metrics were being recorded better, so that the topic and partition are part of the JMX query as oppose to part of the attribute name. So I don't really need this feature myself now, not sure if you'd still like the issue open incase its a feature you'd like to be added @robvadai if not i can close this issue?

**Comment by robvadai** [comment]
Nobody upvoted this ticket yet so let's close the ticket for now.
Thank you for your feedback.
