### ISSUE TITLE
Migration to Kamon 2

### ISSUE THREAD

**Issue by sebarys** [Segence/kamon-jmx-collector#34]
Hello,

At the beggining big thanks for developing this library, it is very useful :)
Is there a plan of migration to Kamon 2.x?
Kamon 1.x currently is supporting only Scala 2.12 so if we would like migrate to Scala 2.13 migration to Kamon 2.x is required :(

Regards

**Comment by robvadai** [comment]
Hi there,

this PR will solve this: https://github.com/Segence/kamon-jmx-collector/pull/32

At the moment the issue is that Travis stopped working for this repo but once it's fixed the artifact will be published.

**Comment by robvadai** [comment]
Hi @sebarys,

version `1.0.0-RC1` is released, can you test it please.

Thanks
